# Generated by Django 2.2.4 on 2022-02-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploded_by',
            new_name='uploaded_by',
        ),
    ]
